services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    depends_on:
      - web-app
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/configs:/configs
      - ./reverse-proxy/log:/var/log/nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - app-net

  # Vue app
  web-app:
    image: "web-app:v1.0.31"
    build:
      context: evergreen_yp_ems_website
      dockerfile: Dockerfile
    container_name: web-app
    expose:
      - "80"
    restart: always
    networks:
      - app-net

  # Backend API
  web-api:
    image: "web-api:v1.0.20"
    build:
      context: ./evergreen_yp_ems_backend_api_local
      dockerfile: Dockerfile
    container_name: web-api
    restart: always
    expose:
      - 5000
    environment:
      - TZ=Asia/Taipei
    env_file:
      - ./evergreen_yp_ems_backend_api_local/.env
    mem_limit: 4GB
    command: [ "python", "apps/dashboard/__init__.py" ]
    volumes:
      - ./evergreen_yp_ems_backend_api_local/logs:/app/logs
      - ./evergreen_yp_ems_backend_api_local/docs:/app/docs
      - /home/femc/project/share_folder:/app/share_folder
      - /mnt/nas/storage:/app/data
    networks:
      - app-net

 # Ref615 API
  relay-api:
    image: "ref615-api:v1.0.2"
    build:
      context: ./ref615-api
      dockerfile: Dockerfile
    container_name: ref615-api
    restart: always
    expose:
      - 5000
    environment:
      - TZ=Asia/Taipei
      - ENV LD_LIBRARY_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app"
    mem_limit: 4GB
    command: ["dotnet", "Relay-REF615-API.dll"]
    volumes:
      - ./ref615-api/logs:/app/logs
      - ./ref615-api/data:/app/temp_folder
      - ./ref615-api/Relay-REF615-API/appsettings.json:/app/appsettings.json
      - /home/femc/project/share_folder:/app/share_folder
      - /mnt/nas/storage:/app/data
    networks:
      - app-net

  # Web-Socket
  web-socket-server:
    image: "web-socket:v1.0.2"
    container_name: web-websocket-server
    build:
      context: ./evergreen_yp_ems_web_socket_server
      dockerfile: Dockerfile
    restart: always
    expose:
      - 8009
    ports:
      - 8009:8009
    environment:
      - TZ=Asia/Taipei
    command: ["python", "main.py"]
    volumes:
      - ./evergreen_yp_ems_web_socket_server/logs:/app/logs
      - ./evergreen_yp_ems_web_socket_server/config.ini:/app/config.ini
      - ./evergreen_yp_ems_web_socket_server/config:/app/config
      - /mnt/nas/storage:/app/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    external: false
  internal-net:
    driver: bridge
    external: false