[SETTINGS]
logging_level = info
field_name = EVEYP
field_id = 69327beb72618fde12ee0ac4
case_id =
mongo_settings = MONGODB_SETTINGS
zip_file_enable = False
show_device_data = False
; --- 將告警變數儲存到csv資料 ---
log_warning_data_to_csv_enable = False
; --- 如果是非群組告警變數，其數值如果為1則自動告警 ---
auto_non_group_warning_variable_enable = False
; --- 如果是群組告警變數，其數值如果為1則自動告警 ---
auto_group_warning_variable_enable = False

[ESS]
rack_number_per_container = 6
pack_number_per_rack = 8
cell_series_number_per_pack = 52
cell_parallel_number_per_pack = 2
cell_volt_number_per_pack = 52
cell_temp_number_per_pack = 36
cell_terminal_temp_number_per_pack = 12
cell_soc_number_per_pack = 52
cell_soh_number_per_pack = 52

[METER_SUN2]
resource_id = evergreen-yp
parent_id =
equipment_id = METER_SUN2

[MONGODB_SETTINGS]
host = 192.168.100.105
port = 27017
username = root
password = 1qaz@WSX-pl,)OKM
database_name = FEMC_EMS_LOCAL_EVEYP
