from enum import Enum


class ConfigConstant(Enum):
    STORAGE = 'storage'
    USING = 'using'
    CONN_TYPE = 'conn_type'
    DATABASE = 'database'
    POSTGRES = 'postgres'
    MONGODB = 'mongodb'
    MSSQL = 'mssql'
    MODBUS = 'modbus'
    IEC61850 = 'iec61850'
    FILESYSTEM = 'filesystem'
    URI = 'uri'
    PORT = 'port'
    USERNAME = 'username'
    PWD = 'password'
    DATABASE_NAME = 'database_name'
    REPLICASET = 'replicaset'
    REPLICASET_LIST = 'replicaset_list'
    SLAVE_ID = 'slave_id'
    CABINET = 'cabinet'
    KEY = 'key'
    LOCALDB = 'localdb'
    BASE_PATH = 'base_path'
    APP = 'app'
    HOST = 'host'
    VERSION = 'version'
    LOCAL = 'local'
    LOG_PATH = 'log_path'
    TEMP_FOLDER = 'temp_folder'
    SECURITY_AUTH = 'security_auth'
    REQUEST_HEADER = 'request_header'
    SECRET_KEY = 'secret_key'
    SESSION_KEY = 'session_key'
    AUTH_ENABLE = 'auth_enable'
    OTP_AES_KEY = 'otp_aes_key'
    AUTH_LIFE = 'auth_life'
    FIELD_ID = 'field_id'
    TOKEN_ID = 'token_id'
    ID = 'id'
    SMB_USER = 'smb_user'
    SMB_PWD = 'smb_pwd'
    SINGLE_LOGIN = 'single_login'
