[SETTINGS]
executor_id = 64b8a4601ef5535d560521db
job_id = tasco_batch_charge_report
source = FILE_SOURCE
destination = TASCO_EMS

;0:不開啟重複執行, 1:重複執行(重複執行不可帶預設參數)
use_schedule = true

;重複執行模式: cron/interval
schedule_type = interval

;固定時間執行參數
cron_day_of_week = *
cron_hour = *
cron_minute = 45
cron_second = 0-1

;間隔時間執行模式:
;seconds/minutes/hours/days/weeks
interval_unit = seconds
interval_value = 5

[SLACK_MESSAGE]
title = TASCO-ECI Calculator
; enable: 1=true, 0=false
enable = 1
slack_bot_token = xoxb-3721238476737-3708842109779-RwdrbzxRRwyKU0WYJns1TBrH
channel = prd-tasco
notify_who = LuisYang,WilsonWu,DannyChiu,AlvinChang

[LOGGER]
logging_level = INFO
logging_path = ./Log
log_to_db = false
; 若log_to_db為True時，連線設定
db_type = mongo
uri = 127.0.0.1
port = 27017
username = root
password = 1qaz@WSX-pl,)OKM
database_name = FORMOSA_OIL
sid = XE
schema_name =
replicaset =
replicaset_list =
lib_dir = C:\Users\User\Desktop\vm_share_folder\instantclient-basic-windows.x64-21.10.0.0.0dbru\instantclient_21_10\

[FILE_SOURCE]
db_type = filesystem
uri = /app/data
port =
username =
password =
database_name =
sid =
schema_name =
replicaset =
replicaset_list =
lib_dir =

[TASCO_EMS]
db_type = mongo
uri =
port =
username =
password =
database_name = FEMC_EMS_LOCAL
sid =
schema_name =
replicaset =rs-config-server
replicaset_list =192.168.100.51:27017,192.168.100.52:27017
lib_dir =
