services:
  modbus-proxy:
    image: "femc/femc-modbus-proxy:v1.0.0"
    container_name: "pcs_proxy"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Taipei
    restart: always
    volumes:
      - ./modbus_proxy.yaml:/app/modbus_proxy.yaml
      - ./log-verbose.conf:/app/log-verbose.conf
      - /mnt/nas/storage:/app/data
    ports:
      - 6000:6000
      - 6001:6001
