services:
  modbus-reader:
    image: "femc/femc-modbus-reader:latest"
    container_name: 'bmu_1_reader'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config:/app/config
      - ./modbus_config:/app/modbus_config
      - ./plugins:/app/plugins
      - /mnt/nas/storage:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Taipei
    command: python main.py
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"