[SETTINGS]
executor_id = 64b8a4601ef5535d560521db
job_id = job_09_sr_process_control
source = FEMC_MODBUS
destination = ADVANCED_EMS
database = ADVANCED_EMS
field_id = 65449a6ec1d454045700f65c
case_id = ATSCKS
field_key = 6633c0_gp_advanced_ks
auth_key = 099c7a76b
sync_uri = https://ems.femctw.com/api/v1/
token_head = Femc-Access-Token
parameters = rack_vol_count:52|rack_temp_count:36|rack_terminal_temp_count:12
run_sdate =
run_edate =

;0:不開啟重複執行, 1:重複執行(重複執行不可帶預設參數)
use_schedule = true

;重複執行模式: cron/interval
schedule_type = interval

;固定時間執行參數
cron_day_of_week = *
cron_hour = *
cron_minute = *
cron_second = 0,10,20,30,40,50

;間隔時間執行模式:
;seconds/minutes/hours/days/weeks
interval_unit = seconds
interval_value = 5

[HEARTBEAT]
enable=0
health_check=0
listen_ip=0.0.0.0
listen_port=6620
proportion=2500
interval=5
destinations=192.168.100.102:6620

[FEMC_NOTIFY]
enable = 0
title = Adv-Tek-ESSCI Batch
url = https://ems-message.femctw.com:443/api/msg_srv/messages
header_key = femc-secret-key
secret_key = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBfZGF0ZSI6MTc0MzUxMjQ1Mi40NTMxOH0.MXUnlgrxgyJVMaRNOnvE4yaxzieUFEgT5KlDaGN2TbA

[LOGGER]
logging_level = INFO
logging_path = ./Log
log_to_db = false
; 若log_to_db為True時，連線設定
db_type = mongo
uri = 192.168.100.105
port = 27017
username = root
password = 1qaz@WSX-pl,)OKM
database_name = FEMC_EMS_LOCAL
sid =
schema_name =
replicaset =
replicaset_list =
lib_dir =

[FILE_SOURCE]
db_type = filesystem
uri = /app/data
port =
username =
password =
database_name =
sid =
schema_name =
replicaset =
replicaset_list =
lib_dir =

[ADVANCED_EMS]
db_type = mongo
uri = 192.168.100.105
port = 27017
username = root
password = 1qaz@WSX-pl,)OKM
database_name = FEMC_EMS_LOCAL
sid =
schema_name =
replicaset =
replicaset_list =
lib_dir =

[FEMC_MODBUS]
db_type = modbus
uri = 192.168.100.103
port = 502
username =
password =
database_name =
sid = 1
schema_name =
replicaset =
replicaset_list =
lib_dir =

[PCS]
db_type = modbus
uri = 192.168.100.103
port = 6000
username =
password =
database_name =
sid = 1
schema_name =
replicaset =
replicaset_list =
lib_dir =

[BMS_1]
db_type = modbus
uri = 192.168.100.103
port = 6001
username =
password =
database_name =
sid = 1
schema_name =
replicaset =
replicaset_list =
lib_dir =

[METER_MAIN]
db_type = modbus
uri = 192.168.100.103
port = 6004
username =
password =
database_name =


