[SETTINGS]
executor_id = 64b8a4601ef5535d560521db
job_id = job_00_status_control
source = FILE_SOURCE
destination = ADVANCED_EMS
database = ADVANCED_EMS
field_id = 65449a6ec1d454045700f65c
case_id = ATSCKS
field_key = 6633c0_gp_advanced_ks
auth_key = 099c7a76b
sync_uri = https://ems.femctw.com/api/v1/
token_head = Femc-Access-Token
parameters = rack_vol_count:52|rack_temp_count:36|rack_terminal_temp_count:12
run_sdate =
run_edate =

;0:不開啟重複執行, 1:重複執行(重複執行不可帶預設參數)
use_schedule = true

;重複執行模式: cron/interval
schedule_type = interval

;固定時間執行參數
cron_day_of_week = *
cron_hour = *
cron_minute = *
cron_second = 0

;間隔時間執行模式:
;seconds/minutes/hours/days/weeks
interval_unit = seconds
interval_value = 5

[HEARTBEAT]
enable=0
health_check=0
listen_ip=0.0.0.0
listen_port=6620
proportion=2500
interval=5
destinations=192.168.100.102:6620

[FEMC_NOTIFY]
enable = 0
title = Adv-Tek-ESSCI Batch
url = https://ems-message.femctw.com:443/api/msg_srv/messages
header_key = femc-secret-key
secret_key = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBfZGF0ZSI6MTc0ODc2Mjk0OC4zODY0OTN9.OserT4NABA9SevjQx2GHsAQOZDz4eVRcO9J6Ew7W0e4

[LOGGER]
logging_level = INFO
logging_path = ./Log
log_to_db = false
; 若log_to_db為True時，連線設定
db_type = mongo
uri = 192.168.100.105
port = 27017
username = root
password = 1qaz@WSX-pl,)OKM
database_name = FEMC_EMS_LOCAL
sid =
schema_name =
replicaset =
replicaset_list =
lib_dir =

[FILE_SOURCE]
db_type = filesystem
uri = /app/data
port =
username =
password =
database_name =
sid =
schema_name =
replicaset =
replicaset_list =
lib_dir =

[ADVANCED_EMS]
db_type = mongo
uri = 192.168.100.105
port = 27017
username = root
password = 1qaz@WSX-pl,)OKM
database_name = FEMC_EMS_LOCAL
sid =
schema_name =
replicaset =
replicaset_list =
lib_dir =

[FEMC_MODBUS]
db_type = modbus
uri = 192.168.100.103
port = 502
username =
password =
database_name =
sid = 1
schema_name =
replicaset =
replicaset_list =
lib_dir =

[FEMC_MQTT]
db_type = mqtt
uri = 10.10.40.10
;aqvprzxfs1252-ats.iot.ap-northeast-1.amazonaws.com
port = 1883
;8883
username = lab01
password = p@ssW0rd
client_id = ""
;可多個topic, 使用 | 分割
topic = data/solar/ipc0001/src_ip=192.168.128.16/dev
will_message = will/solar/ipc0001/src_ip=192.168.128.16/dev
;qos說明 0:最多一次, 1:至少一次, 2:只有一次
qos = 1
use_ssl = False
ca =
client_cert =
client_kry =
retain = False

[PCS]
db_type = modbus
uri = 192.168.100.103
port = 6000
username =
password =
database_name =
sid = 1
schema_name =
replicaset =
replicaset_list =
lib_dir =

[BMS_1]
db_type = modbus
uri = 192.168.100.103
port = 6002
username =
password =
database_name =
sid = 1
schema_name =
replicaset =
replicaset_list =
lib_dir =

[BMS_2]
db_type = modbus
uri = 192.168.100.103
port = 6003
username =
password =
database_name =
sid = 1
schema_name =
replicaset =
replicaset_list =
lib_dir =

[SUN_IO]
db_type = modbus
uri = 127.0.0.1
port = 502
username =
password =
database_name =
sid = 0
schema_name =
replicaset =
replicaset_list =
lib_dir =

