version: "3.8"

services:
  server:
    image: "femc/femc-batch-scheduler:v1.0.0"
    container_name: "job-94-alarm-notify"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Taipei
    command: ["python", "main.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs
      - ./config.ini:/app/config.ini
      - /mnt/nas/storage:/app/data
      - ./configs:/app/configs
      - /home/femc/project/share_folder:/app/share_folder
